### ISSUE TITLE
"return" may be wrongly used

### ISSUE THREAD

**Issue by NotOneRing** [fahrbach/icml-2020-faster-graph-embeddings#1]
Dear author,

Could you please explain these few lines of code in "GreedyRandomContractions" from the file "random-contraction.cc":
    // Trying target min degree
    if (adj[node].size() > TARGET_DEGREE) return;

Should the "return" command be replaced by "continue;" or something else?

if you "return" this function here, all remained nodes are not processed, but you haven't ranked them by their nodes. How could you guarantee that all remaining nodes are of a degree larger than TARGET_DEGREE, which is 30 as a default parameter in your code.

**Comment by fahrbach** [comment]
Hi NotOneRing,

The `min_degree_set` maintains the current degree of each node at every point of the algorithm sorted in increasing order. The loop starts by finding the min degree node (`int node = (*min_degree_set.begin()).second;`). If this is larger than the global threshold of `TARGET_DEGREE`, we are guaranteed that all other nodes have degree at least as large as `node`.

I think we're safe here, but I agree it's unclear due to the global `min_degree_set` data structure.

**Comment by NotOneRing** [comment]
Dear author,

Thanks so much for your reply. I'm still quite confused about the description of increasing order, this function is the only place where the variable "min_degree_set" appears. I haven't discovered any line of code finishing the operation "sort" or place the values in this variable in increasing order. Could you please give more explanation about this "sort" operation?

<img width="731" alt="image" src="https://user-images.githubusercontent.com/86668994/175101191-5d9ded62-6236-45fa-9563-99589879e6d4.png">

**Comment by NotOneRing** [comment]
Dear author,

Globally I didn't find this operation to rank all nodes by their degrees, too.

These are the functions finished before the function "GreedyRandomContractions". For both the link prediction task and the node classification task, I have also read other codes of other functions before this step and this file to preprocess networks(or graphs) and haven't found this "sorting by degree" operation. 

<img width="616" alt="image" src="https://user-images.githubusercontent.com/86668994/175101788-ea8c3cfe-ba66-416c-a018-813af02a6bb0.png">

**Comment by fahrbach** [comment]
Sure. We define `std::set<std::pair<int, int>> min_degree_set;` globally in `random-contraction.cc`. This set's first element is always the node with minimum degree because it's a balanced binary search tree with elements in increasing order of `(degree, node_index)`. Does that clear things up?

**Comment by NotOneRing** [comment]
Okay. Thanks so much for your explanation!

**Comment by fahrbach** [comment]
No problem. Does that clear things up? I think it's doing what's intended -- contracting the graph by the min-degree node until all nodes have degree >= 30.

**Comment by NotOneRing** [comment]
Sure. Thanks so much for your reply! It indeed clears things up! I have one more question about the paper: could the "largest connected component" constraint be removed? Will the algorithm work (may not that much effectively) without this constraint?

**Comment by fahrbach** [comment]
No problem. I'm glad you reached out!

Re largest connected component: If I remember correctly, it has to do with the truncated SVD. Since we want d-dimensional embeddings, we're finding the ~best rank-d approximation of each connected component by computing this for each component separately. Alternatively, if we compute the truncated SVD for the whole graph, then we have the "share" the rank across all components.

An extreme example: If we have n isolated points but want a d-dimensional embedding, this routine effectively keeps d nodes and drops the other n-d.

I can take a closer look later. It's been a while, and what I wrote may not be entirely correct. I think this was the problem though.

**Comment by NotOneRing** [comment]
Thanks so much for your further explanation! I wonder if It means: If I random sample the target nodes and take the whole graph(which may not consist of only one connected component) as a replacement of "the largest connected component" as the "network" file for each dataset to do the embedding, the algorithm still works.
